Repository 7-final-project/message, pull requests merged in 2025-01, with the labels that each got.

#7 메세지 서비스 대기 5번째 고객 알림 발송 기능
  build.gradle
  src/main/java/com/qring/message/application/v1/service/SlackServiceV1.java
  src/main/java/com/qring/message/infrastructure/config/KafkaConsumerConfig.java
  src/main/java/com/qring/message/infrastructure/messaging/kafka/KafkaMessageConsumerV1.java
  src/main/java/com/qring/message/presentation/v1/controller/MessageControllerV1.java
  src/main/resources/application-dev.yml
Labels: ✨ Feature, 🌐 API

#13 application-prod.yml 수정 요구 사항 반영
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ⚙ Setting, ✨ Feature, 🚀 Deploy

#16 ERROR 및 주석 리팩토링
  src/main/java/com/qring/message/application/v1/service/MessageServiceV1.java
  src/main/java/com/qring/message/application/v1/service/SlackServiceV1.java
  src/main/java/com/qring/message/infrastructure/messaging/kafka/KafkaMessageConsumerV1.java
Labels: 🔨 Refactor

#18 운영 환경 설정을 위한 prod.yml 파일 재구성
  src/main/java/com/qring/message/application/res/MessageSearchResDTOV1.java
  src/main/java/com/qring/message/application/service/MessageServiceV1.java
  src/main/java/com/qring/message/application/service/SlackServiceV1.java
  src/main/java/com/qring/message/application/v1/res/MessageGetByIdResDTOV1.java
  src/main/java/com/qring/message/application/v1/res/MessagePostResDTOV1.java
  src/main/java/com/qring/message/infrastructure/docs/MessageControllerSwagger.java
  src/main/java/com/qring/message/infrastructure/messaging/kafka/KafkaMessageConsumerV1.java
  src/main/java/com/qring/message/presentation/controller/MessageControllerV1.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/com/qring/message/MessageApplicationTests.java
Labels: ⚙ Setting, 🔨 Refactor
